name: untitled
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#--------- package ---------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  lottie: ^3.2.0
  connectivity_plus: ^6.1.3
  bloc:
  flutter_bloc:
  dio:
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1

#---------- ./ PACKAGES END ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ---------#
  assets:
    - assets/images/
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/email_varification_images/
    - assets/images/reset_Password_ images/ # Fixed typo here
    - assets/images/banners/
    - assets/images/product/
    - assets/images/user/
    - assets/images/design images/
    - assets/images/selection images/
    - assets/animation/
  #--------- LOCAL FONTS --------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 800
          style: italic
