// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QDXfW1Zae00cubmcfTBt9hBV7I4golU',
    appId: '1:14801529715:web:23026d7ef099ad5289b306',
    messagingSenderId: '14801529715',
    projectId: 'ix7-clothng-app',
    authDomain: 'ix7-clothng-app.firebaseapp.com',
    storageBucket: 'ix7-clothng-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexX3OOYDizX8O9XOl-XIqK1OL8Ku_YnM',
    appId: '1:14801529715:android:6269f622483abcbf89b306',
    messagingSenderId: '14801529715',
    projectId: 'ix7-clothng-app',
    storageBucket: 'ix7-clothng-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFk8JraZOfbPU81jZ5954DILhAvfn7Vl4',
    appId: '1:14801529715:ios:c137e72d7ea1132889b306',
    messagingSenderId: '14801529715',
    projectId: 'ix7-clothng-app',
    storageBucket: 'ix7-clothng-app.firebasestorage.app',
    androidClientId: '14801529715-u7vao9f23u0l6aqr97eq3h4d5usl3dbk.apps.googleusercontent.com',
    iosClientId: '14801529715-807fsoqfe128atc6ro7d5q76dfdf2oo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFk8JraZOfbPU81jZ5954DILhAvfn7Vl4',
    appId: '1:14801529715:ios:c137e72d7ea1132889b306',
    messagingSenderId: '14801529715',
    projectId: 'ix7-clothng-app',
    storageBucket: 'ix7-clothng-app.firebasestorage.app',
    androidClientId: '14801529715-u7vao9f23u0l6aqr97eq3h4d5usl3dbk.apps.googleusercontent.com',
    iosClientId: '14801529715-807fsoqfe128atc6ro7d5q76dfdf2oo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QDXfW1Zae00cubmcfTBt9hBV7I4golU',
    appId: '1:14801529715:web:0a61add9847e607289b306',
    messagingSenderId: '14801529715',
    projectId: 'ix7-clothng-app',
    authDomain: 'ix7-clothng-app.firebaseapp.com',
    storageBucket: 'ix7-clothng-app.firebasestorage.app',
  );

}